[package]
name = "load_links"
version = "0.1.0"
edition = "2024"

[dependencies]
database_api = { path = "../../backend/database_api" }
what_anime_shared = { path = "../../backend/what_anime_shared" }
dotenvy = "0.15.7"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
