[package]
name = "what_anime_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.3", features = ["macros", "postgres"] }
